parameters:
    currency_exchange.cache.cache_lifetime: 3

services:
    currency_exchange.cache.cache_adapter:
        class: Symfony\Component\Cache\Adapter\FilesystemAdapter

    currency_exchange.service.currency_exchange_service:
        class: CurrencyExchangeBundle\Service\ExchangeRateService
        arguments:
            - '@currency_exchange.cache.cache_adapter'
            - '%currency_exchange.cache.cache_lifetime%'

    currency_exchange.service.exchange_rate_provider.fixer:
        class: CurrencyExchangeBundle\ExchangeRateProvider\Provider\FixerExchangeRateProvider
        tags:
            - { name: exchange.rate.provider }

    currency_exchange.service.exchange_rate_provider.google:
        class: CurrencyExchangeBundle\ExchangeRateProvider\Provider\GoogleExchangeRateProvider
        tags:
              - { name: exchange.rate.provider }